# Generated by Django 3.2.4 on 2021-09-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileauth'),
        ('budgeting', '0005_costofsales_costtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicCostTypeName', models.CharField(max_length=100, null=True, verbose_name='نوع هزینه')),
            ],
            options={
                'verbose_name': 'نوع هزینه عمومی، اداری',
                'verbose_name_plural': 'نوع هزینه عمومی، اداری',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='موضوع مالیات')),
                ('realTaxQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realTaxQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realTaxQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realTaxQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastTaxQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastTaxQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastTaxQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastTaxQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currency')),
            ],
            options={
                'verbose_name': 'مالیات',
                'verbose_name_plural': 'مالیات',
            },
        ),
        migrations.CreateModel(
            name='PublicCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='موضوع هزینه')),
                ('realPublicCostQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realPublicCostQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realPublicCostQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realPublicCostQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastPublicCostQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastPublicCostQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastPublicCostQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastPublicCostQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('isInGroupe', models.BooleanField(default=0, verbose_name='هزینه درون گروهی')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currency')),
                ('publicCostType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.publiccosttype')),
            ],
            options={
                'verbose_name': 'هزینه عمومی، اداری',
                'verbose_name_plural': 'هزینه عمومی، اداری',
            },
        ),
        migrations.CreateModel(
            name='NonOprationalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonOprationIncom', models.CharField(max_length=100, null=True, verbose_name='موضوع درامدی')),
                ('realNonOprationIncomeQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realNonOprationIncomeQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realNonOprationIncomeQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realNonOprationIncomeQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastNonOprationIncomeQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastNonOprationIncomeQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastNonOprationIncomeQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastNonOprationIncomeQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('isInGroupe', models.BooleanField(default=0, verbose_name='درآمد درون گروهی')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currency')),
            ],
            options={
                'verbose_name': 'درآمدهای غیر عملیاتی',
                'verbose_name_plural': 'درآمدهای غیر عملیاتی',
            },
        ),
        migrations.CreateModel(
            name='NonOprationalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='موضوع هزینه')),
                ('realNonOprationCostQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realNonOprationCostQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realNonOprationCostQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realNonOprationCostQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastNonOprationCostQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastNonOprationCostQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastNonOprationCostQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastNonOprationCostQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('isInGroupe', models.BooleanField(default=0, verbose_name='هزینه درون گروهی')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currency')),
            ],
            options={
                'verbose_name': 'هزینه های غیر عملیاتی',
                'verbose_name_plural': 'هزینه های غیر عملیاتی',
            },
        ),
        migrations.CreateModel(
            name='LoanCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='موضوع هزینه مالی')),
                ('realLoanCostQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realLoanCostQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realLoanCostQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realLoanCostQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastLoanCostQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastLoanCostQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastLoanCostQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastLoanCostQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currency')),
            ],
            options={
                'verbose_name': 'هزینه مالی',
                'verbose_name_plural': 'هزینه مالی',
            },
        ),
        migrations.CreateModel(
            name='EtcOprationalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etcOprationIncome', models.CharField(max_length=100, null=True, verbose_name='موضوع درامدی')),
                ('realetcOprationIncomeQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realetcOprationIncomeQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realetcOprationIncomeQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realetcOprationIncomeQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastetcOprationIncomeQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastetcOprationIncomeQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastetcOprationIncomeQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastetcOprationIncomeQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('isInGroupe', models.BooleanField(default=0, verbose_name='درآمد درون گروهی')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currency')),
            ],
            options={
                'verbose_name': 'سایر درآمدهای عملیاتی',
                'verbose_name_plural': 'سایر درآمدهای عملیاتی',
            },
        ),
        migrations.CreateModel(
            name='EtcOprationalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='موضوع هزینه')),
                ('realEtcOprationCostQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realEtcOprationCostQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realEtcOprationCostQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realEtcOprationCostQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastEtcOprationCostQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastEtcOprationCostQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastEtcOprationCostQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastEtcOprationCostQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('isInGroupe', models.BooleanField(default=0, verbose_name='هزینه درون گروهی')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currency')),
            ],
            options={
                'verbose_name': 'سایر هزینه های عملیاتی',
                'verbose_name_plural': 'سایر هزینه های عملیاتی',
            },
        ),
    ]
