# Generated by Django 3.2.4 on 2021-09-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0007_rename_publiccosttypename_publiccosttype_publiccosttypename'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currencyRate',
            field=models.IntegerField(default=1, verbose_name='نرخ تبدیل به ریال'),
        ),
        migrations.AddField(
            model_name='currency',
            name='yearOfForcast',
            field=models.IntegerField(default=1400),
        ),
    ]
