# Generated by Django 3.2.4 on 2021-10-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileauth'),
        ('budgeting', '0008_auto_20210909_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAssetsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentAssetName', models.CharField(max_length=100, verbose_name='نام حساب')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('accountCode', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'نوع دارایی جاری',
                'verbose_name_plural': 'نوع دارایی جاری',
            },
        ),
        migrations.CreateModel(
            name='CurrentLiabilitiesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentAssetName', models.CharField(max_length=100, verbose_name='نام حساب')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('accountCode', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'نوع بدهی جاری',
                'verbose_name_plural': 'نوع بدهی جاری',
            },
        ),
        migrations.CreateModel(
            name='NonCurrentAssetsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentAssetName', models.CharField(max_length=100, verbose_name='نام حساب')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('accountCode', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'نوع دارایی غیر جاری',
                'verbose_name_plural': 'نوع دارایی غیر جاری',
            },
        ),
        migrations.CreateModel(
            name='NonCurrentLiabilitiesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentAssetName', models.CharField(max_length=100, verbose_name='نام حساب')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('accountCode', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'نوع بدهی غیر جاری',
                'verbose_name_plural': 'نوع بدهی غیر جاری',
            },
        ),
        migrations.CreateModel(
            name='PropertyRightsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentAssetName', models.CharField(max_length=100, verbose_name='نام حساب')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('accountCode', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'نوع حقوق مالکانه',
                'verbose_name_plural': 'نوع حقوق مالکانه',
            },
        ),
        migrations.CreateModel(
            name='PropertyRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currentAssetType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.propertyrightstype')),
            ],
            options={
                'verbose_name': 'حقوق مالکانه',
                'verbose_name_plural': 'حقوق مالکانه',
            },
        ),
        migrations.CreateModel(
            name='NonCurrentLiabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currentAssetType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.noncurrentliabilitiestype')),
            ],
            options={
                'verbose_name': 'بدهی غیر جاری',
                'verbose_name_plural': 'بدهی غیر جاری',
            },
        ),
        migrations.CreateModel(
            name='NonCurrentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currentAssetType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.noncurrentassetstype')),
            ],
            options={
                'verbose_name': 'دارایی غیر جاری',
                'verbose_name_plural': 'دارایی غیر جاری',
            },
        ),
        migrations.CreateModel(
            name='CurrentLiabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currentAssetType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currentliabilitiestype')),
            ],
            options={
                'verbose_name': 'بدهی جاری',
                'verbose_name_plural': 'بدهی جاری',
            },
        ),
        migrations.CreateModel(
            name='CurrentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realQ1', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('realQ2', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه دوم')),
                ('realQ3', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه سوم')),
                ('realQ4', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه چهارم')),
                ('forcastQ1', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه اول')),
                ('forcastQ2', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه دوم')),
                ('forcastQ3', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه سوم')),
                ('forcastQ4', models.IntegerField(default=0, verbose_name='مقدار پیش بینی سه ماهه چهارم')),
                ('yearOfForcast', models.IntegerField(default=1400)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('currentAssetType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='budgeting.currentassetstype')),
            ],
            options={
                'verbose_name': 'دارایی جاری',
                'verbose_name_plural': 'دارایی جاری',
            },
        ),
    ]
