# Generated by Django 3.2.4 on 2021-10-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0010_auto_20211020_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentliabilities',
            old_name='currentAssetType',
            new_name='currentLbltType',
        ),
        migrations.RenameField(
            model_name='currentliabilitiestype',
            old_name='currentAssetName',
            new_name='currentLbltName',
        ),
    ]
