# Generated by Django 3.2.4 on 2021-10-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0012_auto_20211022_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyrights',
            old_name='currentAssetType',
            new_name='prprtyRightsType',
        ),
        migrations.RenameField(
            model_name='propertyrightstype',
            old_name='currentAssetName',
            new_name='prprtyRightsName',
        ),
    ]
