# Generated by Django 3.2.4 on 2021-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0013_auto_20211022_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='realIncomeQ1',
            field=models.PositiveIntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول'),
        ),
    ]
