# Generated by Django 3.2.4 on 2022-03-22 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileauth'),
        ('budgeting', '0014_alter_income_realincomeq1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='budgeting')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceMegaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetsAffectedbyInflationBookValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('AssetsAffectedbyInflationFairValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('Capital', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('CapitalBelongstoPEDC', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('CapitalChange', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('COGs', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('Dividends', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('DPS', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('Earning', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('EPS', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('EquityBookValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('EquityFairValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('EquityBooKValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('FaceValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('GovernanceDivision', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('GrossProfit', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('Interest', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('NAV', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('NetProfit', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('NeutralAssetsBookValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('NonoperatingIncomesCosts', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('NumberofSharesBelongtoPEDC', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('OperatingProfit', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('OtherOperatintgIncomesCosts', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('OwnershipofPEDC', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('Portfolio', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('SGA', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('Tax', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TotalAssetBookValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TotalAssetFairValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TotalLiabilitiesBookValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TotalNumberofOutstandingShares', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TotalSaleTotalAssetFV', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TotalSales', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TSRBookValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('TSRFairValue', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('year', models.IntegerField(default=0, verbose_name='مقدار واقعی سه ماهه اول')),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
            ],
        ),
    ]
